### ISSUE TITLE
Colored output out of order on Windows 7

### ISSUE THREAD

**Issue by Rukenshia** [TimonPost/crossterm#32]
Hi,

I'm having an issue with the Windows Command line on Windows 7.

Here's the code:

```
    let crossterm = Crossterm::new();
    ...

    println!("Currently, only Keycloak is supported as Identity Provider. When setting the");
    println!(
        "IDP URL, please note that you will have to pass {} of Keycloak.\n",
        crossterm
            .paint("the exact path to the saml client")
            .with(Color::Yellow)
    );
```

But it gets displayed as this:
![image](https://user-images.githubusercontent.com/1899599/45831396-e2d4aa00-bcc4-11e8-9440-010c64426444.png)

As you can see, the "the exact path to the saml client" gets put to the start of the message. It also seems like the color is cleared to "white" instead of the default gray.

**Comment by TimonPost** [comment]
Hey,

Witch version are you using? I have fixed this in version 4.0 see [this](https://github.com/TimonPost/crossterm/blob/master/docs/ReleaseNotes.md#features--fixes-in-crossterm-040)

Let me know if that works out!

**Comment by Rukenshia** [comment]
Looks like I'm still on 0.3.x, I will update and reopen the issue if it's still a thing. Thanks!

**Comment by Rukenshia** [comment]
Hi, still doesnt work with 0.4.2:

![image](https://user-images.githubusercontent.com/1899599/46093405-dea10480-c17c-11e8-8601-85870f837054.png)

**Comment by TimonPost** [comment]
Strange I think I have time to look at it tomorrow 27/09 let you know!

**Comment by TimonPost** [comment]
I have looked at it but it is working for me so I am not sure if it is because of windows 7. But if you use the following code does it work?

```
fn main()
{
    let screen= Screen::default();
    let crossterm = Crossterm::new(&screen);

    println!(
        "Currently, only Keycloak is supported as Identity Provider. When setting the \n \
          IDP URL, please note that you will have to pass {} of Keycloak.\n",
        crossterm
            .style("the exact path to the saml client")
            .with(Color::Yellow)
            .into_displayable(&screen)
    );
}
```

https://ibb.co/gaSfMp

**Comment by Rukenshia** [comment]
Tried it with your exact code (plus the `use`), same result on Windows 7 (running on an AWS WorkSpace)

![image](https://user-images.githubusercontent.com/1899599/46154659-40c03f00-c23b-11e8-8137-bb758771ba62.png)

**Comment by TimonPost** [comment]
Just to let you know I am working on it finaly got windows 7 installed Ill test it there and see if I can find what the problem is.

**Comment by TimonPost** [comment]
I have moved this to another issue see #38
